### ISSUE TITLE
Sidecars keep reloading even no endpoints change

### ISSUE THREAD

**Issue by addozhang** [flomesh-io/osm-edge#111]
**Bug description**:

The controller kept issuing config data to the sidecar, which resulted in the sidecar reloading regularly.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Sidecar Control Plane      [X]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

Sidecar only reloads on real config updates.

**Steps to reproduce the bug (as precisely as possible)**:

1. clone https://github.com/addozhang/osm-benchmark2. 
2. execute `./demo/run-edge-demo.sh`3. 

**How was osm-edge installed?**:

```
osm install \
    --mesh-name "$MESH_NAME" \
    --osm-namespace "$K8S_NAMESPACE" \
    --verbose \
    --set=osm.enablePermissiveTrafficPolicy=true \
    --set=osm.image.pullPolicy="$IMAGE_PULL_POLICY" \
    --set=osm.enableDebugServer="false" \
    --set=osm.enableEgress="false" \
    --set=osm.enableReconciler="false" \
    --set=osm.deployGrafana="false" \
    --set=osm.deployJaeger="false" \
    --set=osm.tracing.enable="false" \
    --set=osm.enableFluentbit="false" \
    --set=osm.deployPrometheus="false" \
    --set=osm.sidecarLogLevel="$SIDECAR_LOG_LEVEL" \
    --set=osm.controllerLogLevel="trace"
```

**Anything else we need to know?**:

controller log attached bellow.

**Bug report archive**:

**Environment**:
- osm-edge version (use `osm version`): 1.2.0
- Kubernetes version (use `kubectl version`): 1.23
- Size of cluster (number of worker nodes in the cluster): 1 worker node with 16c cpu and 64g mem.
- Others:

[controller.log](https://github.com/flomesh-io/osm-edge/files/9947625/controller.log)

**Comment by cybwan** [comment]
This was fixed in #113
