### ISSUE TITLE
Support Metrics and Tracing

### ISSUE THREAD

**Issue by reaver-flomesh** [flomesh-io/osm-edge#12]
**Please describe the Improvement and/or Feature Request**

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- PIPY Control Plane [x]
- CLI Tool                   [ ]
- Metrics                    [x]
- Tracing                    [x]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

Need to figure out:
- If metrics and tracing ingestion still works with the new pipy implementation
- If Grafana and Jaeger dashboard are still able to show data correctly

If find any broken, please try to fix it.

**Comment by caishu97** [comment]
close #12 and #7, and use new issue for tracing and metrics instead
