### ISSUE TITLE
CPU/memory configuration of the sidecar for namespace

### ISSUE THREAD

**Issue by Flomesh-Jade** [flomesh-io/osm-edge#127]
**Feature Request Description:**

The CPU/memory configuration of the sidecar can be globally configured for different namespace.
And these sidecar configurations of each deployment could be modified separately.

**Scope (please mark with X where applicable)**
- New Functionality          [X]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
Different services have different performance requirements for the sidecar, so the required sidecar configurations are different.

**Comment by cybwan** [comment]
v1.3 has implmented the feature.
