### ISSUE TITLE
Pipy‘s policy json lacks support for grpc protocol

### ISSUE THREAD

**Issue by cybwan** [flomesh-io/osm-edge#9]
**Bug description**:
Pipy‘s policy json generated pipy proxy control plane lacks support for grpc protocol

**Affected area (please mark with X where applicable)**:
- Sidecar Control Plane        [X]

**Expected behavior**:
Pipy sidecar supports grpc protocol

**Steps to reproduce the bug (as precisely as possible)**:
E2E_FLAGS='-ginkgo.focus="gRPC insecure traffic origination over HTTP2 with SMI HTTP routes"' make test-e2e

**How was OSM installed?**:
Compiled osm from source

**Anything else we need to know?**:

**Bug report archive**:

**Environment**: 
- OSM version (use `osm version`): master
- Kubernetes version (use `kubectl version`): v1.20.15
- Size of cluster (number of worker nodes in the cluster): Kind(v0.12.0) Cluster
- Others: Ubuntu 20.04.4 LTS AMD64

**Comment by wanpf** [comment]
Fixed  (pipy main branch commit 24ed0ba937ec79f1c2aefee0033d43b3d44cec04)

**Comment by cybwan** [comment]
Fixed
